[tool.poetry]
name = "reddit-blackout"
version = "0.1.0"
description = "Sets your subreddits to private"
authors = ["opliko"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
praw = "^7.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
